# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-01-22 23:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prsn_line', models.CharField(max_length=40, verbose_name='Line')),
                ('prsn_city', models.CharField(max_length=40, verbose_name='City')),
                ('prsn_state', models.CharField(max_length=2, verbose_name='Sate')),
                ('prsn_zip', models.CharField(max_length=5, verbose_name='Zip')),
            ],
            options={
                'verbose_name': 'Adress',
            },
        ),
        migrations.CreateModel(
            name='AppointmentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appt_title', models.CharField(max_length=60, verbose_name='Title')),
                ('appt_descr', models.TextField()),
                ('appt_date_time', models.DateField()),
                ('appt_last_changed', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PersonModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prsn_fname', models.CharField(max_length=30, verbose_name='First Name')),
                ('prsn_lname', models.CharField(max_length=30, verbose_name='Last Name')),
                ('prsn_phone', models.CharField(max_length=30, verbose_name='Phone')),
                ('prsn_email', models.CharField(max_length=30, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Person',
            },
        ),
        migrations.AddField(
            model_name='appointmentmodel',
            name='prsn_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointmentProApp.PersonModel'),
        ),
        migrations.AddField(
            model_name='addressmodel',
            name='prsn_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointmentProApp.PersonModel', verbose_name='ID'),
        ),
    ]
