# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-01-22 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointmentProApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personmodel',
            name='prsn_email',
            field=models.EmailField(max_length=60, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='personmodel',
            name='prsn_fname',
            field=models.CharField(max_length=20, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='personmodel',
            name='prsn_lname',
            field=models.CharField(max_length=20, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='personmodel',
            name='prsn_phone',
            field=models.CharField(max_length=20, verbose_name='Phone'),
        ),
    ]
